plugins:
  - serverless-dynamodb-local
  - serverless-offline

service: candidate
frameworkVersion: '2'

custom:
  tableName: candidates
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8089
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      dbPath: "./.dynamodb"
      
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: ServelessAccount
  stage: dev
  region: us-east-1
  environment:
    tableName: ${self:custom.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
          - dynamodb:*
      Resource: '*'

package:
  patterns:
    - '!.dynamodb/**'
    - '!.git/**'
    - '!node_modules/**'

functions:
  getUser:
    handler: lambdas/endpoints/getUser.handler
    events:
      - http:
            path: get-user/{ID}
            method: GET
            cors: true
  getPlayerScore:
    handler: lambdas/endpoints/getPlayerScore.handler
    events:
      - http:
            path: get-player-score/{ID}
            method: GET
            cors: true
  createPlayerScore:
    handler: lambdas/endpoints/createPlayerScore.handler
    events:
      - http:
            path: create-player-score/{ID}
            method: POST
            cors: true
  updatePlayerScore:
    handler: lambdas/endpoints/updatePlayerScore.handler
    events:
      - http:
            path: update-player-score/{ID}
            method: POST
            cors: true
  getGameScores:
    handler: lambdas/endpoints/getGameScores.handler
    events:
      - http:
            path: get-game-scores/{game}
            method: GET
            cors: true

resources:
  Resources:
    MyDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: game
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

        GlobalSecondaryIndexes:
            - IndexName: game-index
              KeySchema:
                  - AttributeName: game
                    KeyType: HASH
              Projection:
                    ProjectionType: ALL
